services:
  postgres-db:
    image: postgres:16-alpine
    container_name: meu-postgres-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=aulafull
    volumes:
      - postgres-data-local:/var/lib/postgresql/data

  api-spring:
    container_name: minha-api
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/aulafull
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - postgres-db

volumes:
  postgres-data-local: